import { Project, SourceFile } from 'ts-morph';
import * as fs from 'fs';
import * as path from 'path';

export class ServiceIndexGenerator {
    private project: Project;

    constructor(project: Project) {
        this.project = project;
    }

    generateIndex(servicesDir: string): void {
        const indexPath = path.join(servicesDir, 'index.ts');
        const sourceFile = this.project.createSourceFile(indexPath, '', { overwrite: true });

/*        sourceFile.addText(`/!**
 * Generated service exports
 * Do not edit this file manually
 *!/

`);*/

        // Find all service files
        const serviceFiles = fs.readdirSync(servicesDir)
            .filter(file => file.endsWith('.service.ts'))
            .map(file => file.replace('.service.ts', ''));

        // Add exports
        serviceFiles.forEach(serviceName => {
            const className = this.pascalCase(serviceName) + 'Service';
            sourceFile.addExportDeclaration({
                namedExports: [className],
                moduleSpecifier: `./${serviceName}.service`,
            });
        });

        // Add barrel export
/*        sourceFile.addText(`
// Barrel export for convenience
export const GENERATED_SERVICES = [
${serviceFiles.map(name => `  ${this.pascalCase(name)}Service`).join(',\n')}
];
`);*/

        sourceFile.saveSync();
    }

    private pascalCase(str: string): string {
        return str.replace(/(?:^|[-_])([a-z])/g, (_, char) => char.toUpperCase());
    }
}